name: g1_g2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^3.1.0
  location: ^8.0.1
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  provider: ^6.1.5+1
  shadcn_flutter: ^0.0.44
  shared_preferences: ^2.5.3
  floating_navbar: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  geolocator: ^14.0.2
  uuid: ^4.5.2
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.3
  firebase_storage: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AppIcon/AppIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/vitor.jpg
    #   - images/a_dot_ham.jpeg
